### ISSUE TITLE
blending problem

### ISSUE THREAD

**Issue by szabolcsdombi** [yxdragon/myvi#1]
> In some computer not looks well when set the blend.

I found this line in the README.
I think I could solve this by adding a new feature to ModernGL.
The default blending is `(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)`

What blending settings you may need?

**Comment by yxdragon** [comment]
@cprogrammer1994   Thanks, See [here](https://github.com/Image-Py/imagepy), there is a tooth demo in ImagePy's page. It is draw by mayavi, I can't draw like this use moderngl, I think I should set some color mix mode, I have try some, but failed.  And In some computer, I even cannot see the inner object through the blend surface.

and on mac, I got a shader error, not support 330 version.

**Comment by szabolcsdombi** [comment]
> And In some computer, I even cannot see the inner object through the blend surface

Sounds like the absence of [Transparency Sorting](https://www.khronos.org/opengl/wiki/Transparency_Sorting)

**Comment by szabolcsdombi** [comment]
If transparency sorting does not help you, then help me understand what kind of blending do you need.

**Comment by yxdragon** [comment]
if I put a ball in a transparent cube.

1. in any computer and system, It looks bad in some specific view. (that should be the transparency sorting)

2. on win10, 64bit, wx4.0, I cannot see the ball. (even set transparent to 0, the cube hide, and cannot see the ball)

3. on mac, I got a shader error, not support version 330. 
 
and the sorting work seems must be done on cpu, need I have wrote the sorting algrithsm? and give to the GPU as the right order? If it is hard, it is not nessesary. (vtk and mayavi has the same question)

some question may be wx's bug or system's support, I learn opengl just several days, So I cannot solve them, even donot known why it happends.

**Comment by szabolcsdombi** [comment]
2. Can you paste the code here?
3. Checkout this [list](https://support.apple.com/en-us/HT202823) is your Mac supporting OpenGL 3.3?

**Comment by ramcdougal** [comment]
Could the mac issue be as simple as needing to explicitly request the OpenGL Core Profile? This is sometimes necessary; see e.g. [https://stackoverflow.com/questions/22926779/cannot-use-glsl-330-on-mac-mavericks](url) and [https://stackoverflow.com/questions/19865463/opengl-4-1-under-mavericks?lq=1](url)

I'm not sure how to get ModernGL to do this.

**Comment by szabolcsdombi** [comment]
ModernGL detects the context created by the window. If a standalone context is requested then a core profile will be created.

**Comment by QGB** [comment]
[mayavi 中文介绍](https://documentation.help/py-science-zh/mlab_and_mayavi.html)

![image](https://user-images.githubusercontent.com/8005654/115944574-27fa9180-a4e9-11eb-84d0-e47521a0069e.png)
